# Generated by Django 4.1.3 on 2022-12-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_playerstatus_round_delete_game_playerstatus_round_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='Anonymous141', max_length=180),
        ),
    ]
