# Generated by Django 4.1.3 on 2022-12-06 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_player_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstatus',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
