# Generated by Django 4.1.3 on 2022-12-06 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_playerstatus_score_delete_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='players',
            field=models.ManyToManyField(to='api.player'),
        ),
        migrations.AddField(
            model_name='round',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('closed', 'closed')], max_length=180, null=True),
        ),
    ]
