# Generated by Django 4.1.3 on 2022-12-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_round_players_round_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='decision',
            field=models.CharField(choices=[('rock', 'Rock'), ('paper', 'Paper'), ('scissors', 'Scissors')], max_length=180),
        ),
        migrations.AlterField(
            model_name='playerstatus',
            name='preference',
            field=models.CharField(choices=[('computer', 'Computer'), ('live-player', 'Live Player')], max_length=180),
        ),
    ]
