# Generated by Django 4.1.3 on 2022-12-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_decision_decision_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='status',
        ),
        migrations.AddField(
            model_name='playerstatus',
            name='occupied',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Decision',
        ),
    ]
